### ISSUE TITLE
Update population data

### ISSUE THREAD

**Issue by danfowler** [datasets/population#7]
> Hi, and thanks for some fine data.

> It seems that the [okfn population figures](http://data.okfn.org/data/core/population) stops in 2014, but the original [World Bank source](http://data.worldbank.org/indicator/SP.POP.TOTL)  has data for 2015.

> Would it be possible to update this?

Source: https://github.com/okfn/okfn.github.com/issues/495

**Comment by rufuspollock** [comment]
FIXED.
